/* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var DateTimeMsg_pb = require('./DateTimeMsg_pb.js');
var ProductData_pb = require('./ProductData_pb.js');
goog.exportSymbol('proto.qspace.ProductDetailsMsg', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qspace.ProductDetailsMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.qspace.ProductDetailsMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qspace.ProductDetailsMsg.displayName = 'proto.qspace.ProductDetailsMsg';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qspace.ProductDetailsMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.qspace.ProductDetailsMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qspace.ProductDetailsMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.ProductDetailsMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    product: jspb.Message.getFieldWithDefault(msg, 1, ""),
    vertex: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastUpdated: (f = msg.getLastUpdated()) && DateTimeMsg_pb.DateTimeMsg.toObject(includeInstance, f),
    data: (f = msg.getData()) && ProductData_pb.ProductData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qspace.ProductDetailsMsg}
 */
proto.qspace.ProductDetailsMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qspace.ProductDetailsMsg;
  return proto.qspace.ProductDetailsMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qspace.ProductDetailsMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qspace.ProductDetailsMsg}
 */
proto.qspace.ProductDetailsMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProduct(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVertex(value);
      break;
    case 3:
      var value = new DateTimeMsg_pb.DateTimeMsg;
      reader.readMessage(value,DateTimeMsg_pb.DateTimeMsg.deserializeBinaryFromReader);
      msg.setLastUpdated(value);
      break;
    case 5:
      var value = new ProductData_pb.ProductData;
      reader.readMessage(value,ProductData_pb.ProductData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qspace.ProductDetailsMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qspace.ProductDetailsMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qspace.ProductDetailsMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.ProductDetailsMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProduct();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVertex();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastUpdated();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      DateTimeMsg_pb.DateTimeMsg.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      ProductData_pb.ProductData.serializeBinaryToWriter
    );
  }
};


/**
 * optional string product = 1;
 * @return {string}
 */
proto.qspace.ProductDetailsMsg.prototype.getProduct = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.qspace.ProductDetailsMsg.prototype.setProduct = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string vertex = 2;
 * @return {string}
 */
proto.qspace.ProductDetailsMsg.prototype.getVertex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.qspace.ProductDetailsMsg.prototype.setVertex = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional DateTimeMsg last_updated = 3;
 * @return {?proto.qspace.DateTimeMsg}
 */
proto.qspace.ProductDetailsMsg.prototype.getLastUpdated = function() {
  return /** @type{?proto.qspace.DateTimeMsg} */ (
    jspb.Message.getWrapperField(this, DateTimeMsg_pb.DateTimeMsg, 3));
};


/** @param {?proto.qspace.DateTimeMsg|undefined} value */
proto.qspace.ProductDetailsMsg.prototype.setLastUpdated = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.qspace.ProductDetailsMsg.prototype.clearLastUpdated = function() {
  this.setLastUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.ProductDetailsMsg.prototype.hasLastUpdated = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ProductData data = 5;
 * @return {?proto.qspace.ProductData}
 */
proto.qspace.ProductDetailsMsg.prototype.getData = function() {
  return /** @type{?proto.qspace.ProductData} */ (
    jspb.Message.getWrapperField(this, ProductData_pb.ProductData, 5));
};


/** @param {?proto.qspace.ProductData|undefined} value */
proto.qspace.ProductDetailsMsg.prototype.setData = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.qspace.ProductDetailsMsg.prototype.clearData = function() {
  this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.ProductDetailsMsg.prototype.hasData = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.qspace);
