/* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var DateTimeMsg_pb = require('./DateTimeMsg_pb.js');
goog.exportSymbol('proto.qspace.RateCurveShiftMsg', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qspace.RateCurveShiftMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.qspace.RateCurveShiftMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qspace.RateCurveShiftMsg.displayName = 'proto.qspace.RateCurveShiftMsg';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qspace.RateCurveShiftMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.qspace.RateCurveShiftMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qspace.RateCurveShiftMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.RateCurveShiftMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    isParallel: jspb.Message.getFieldWithDefault(msg, 1, false),
    amount: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    start: (f = msg.getStart()) && DateTimeMsg_pb.DateTimeMsg.toObject(includeInstance, f),
    end: (f = msg.getEnd()) && DateTimeMsg_pb.DateTimeMsg.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qspace.RateCurveShiftMsg}
 */
proto.qspace.RateCurveShiftMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qspace.RateCurveShiftMsg;
  return proto.qspace.RateCurveShiftMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qspace.RateCurveShiftMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qspace.RateCurveShiftMsg}
 */
proto.qspace.RateCurveShiftMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsParallel(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 3:
      var value = new DateTimeMsg_pb.DateTimeMsg;
      reader.readMessage(value,DateTimeMsg_pb.DateTimeMsg.deserializeBinaryFromReader);
      msg.setStart(value);
      break;
    case 4:
      var value = new DateTimeMsg_pb.DateTimeMsg;
      reader.readMessage(value,DateTimeMsg_pb.DateTimeMsg.deserializeBinaryFromReader);
      msg.setEnd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qspace.RateCurveShiftMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qspace.RateCurveShiftMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qspace.RateCurveShiftMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.RateCurveShiftMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsParallel();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getStart();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      DateTimeMsg_pb.DateTimeMsg.serializeBinaryToWriter
    );
  }
  f = message.getEnd();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      DateTimeMsg_pb.DateTimeMsg.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool is_parallel = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.qspace.RateCurveShiftMsg.prototype.getIsParallel = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.qspace.RateCurveShiftMsg.prototype.setIsParallel = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional double amount = 2;
 * @return {number}
 */
proto.qspace.RateCurveShiftMsg.prototype.getAmount = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.qspace.RateCurveShiftMsg.prototype.setAmount = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional DateTimeMsg start = 3;
 * @return {?proto.qspace.DateTimeMsg}
 */
proto.qspace.RateCurveShiftMsg.prototype.getStart = function() {
  return /** @type{?proto.qspace.DateTimeMsg} */ (
    jspb.Message.getWrapperField(this, DateTimeMsg_pb.DateTimeMsg, 3));
};


/** @param {?proto.qspace.DateTimeMsg|undefined} value */
proto.qspace.RateCurveShiftMsg.prototype.setStart = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.qspace.RateCurveShiftMsg.prototype.clearStart = function() {
  this.setStart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.RateCurveShiftMsg.prototype.hasStart = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional DateTimeMsg end = 4;
 * @return {?proto.qspace.DateTimeMsg}
 */
proto.qspace.RateCurveShiftMsg.prototype.getEnd = function() {
  return /** @type{?proto.qspace.DateTimeMsg} */ (
    jspb.Message.getWrapperField(this, DateTimeMsg_pb.DateTimeMsg, 4));
};


/** @param {?proto.qspace.DateTimeMsg|undefined} value */
proto.qspace.RateCurveShiftMsg.prototype.setEnd = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.qspace.RateCurveShiftMsg.prototype.clearEnd = function() {
  this.setEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.RateCurveShiftMsg.prototype.hasEnd = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.qspace);
