/* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var DateTimeMsg_pb = require('./DateTimeMsg_pb.js');
var RateInterpolation_pb = require('./RateInterpolation_pb.js');
goog.exportSymbol('proto.qspace.RateCurveMsg', null, global);
goog.exportSymbol('proto.qspace.RateCurvePoint', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qspace.RateCurvePoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.qspace.RateCurvePoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qspace.RateCurvePoint.displayName = 'proto.qspace.RateCurvePoint';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qspace.RateCurvePoint.prototype.toObject = function(opt_includeInstance) {
  return proto.qspace.RateCurvePoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qspace.RateCurvePoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.RateCurvePoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    date: (f = msg.getDate()) && DateTimeMsg_pb.DateTimeMsg.toObject(includeInstance, f),
    value: +jspb.Message.getFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qspace.RateCurvePoint}
 */
proto.qspace.RateCurvePoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qspace.RateCurvePoint;
  return proto.qspace.RateCurvePoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qspace.RateCurvePoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qspace.RateCurvePoint}
 */
proto.qspace.RateCurvePoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new DateTimeMsg_pb.DateTimeMsg;
      reader.readMessage(value,DateTimeMsg_pb.DateTimeMsg.deserializeBinaryFromReader);
      msg.setDate(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qspace.RateCurvePoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qspace.RateCurvePoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qspace.RateCurvePoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.RateCurvePoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      DateTimeMsg_pb.DateTimeMsg.serializeBinaryToWriter
    );
  }
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional DateTimeMsg date = 1;
 * @return {?proto.qspace.DateTimeMsg}
 */
proto.qspace.RateCurvePoint.prototype.getDate = function() {
  return /** @type{?proto.qspace.DateTimeMsg} */ (
    jspb.Message.getWrapperField(this, DateTimeMsg_pb.DateTimeMsg, 1));
};


/** @param {?proto.qspace.DateTimeMsg|undefined} value */
proto.qspace.RateCurvePoint.prototype.setDate = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.qspace.RateCurvePoint.prototype.clearDate = function() {
  this.setDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.RateCurvePoint.prototype.hasDate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional double value = 2;
 * @return {number}
 */
proto.qspace.RateCurvePoint.prototype.getValue = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.qspace.RateCurvePoint.prototype.setValue = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qspace.RateCurveMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.qspace.RateCurveMsg.repeatedFields_, null);
};
goog.inherits(proto.qspace.RateCurveMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qspace.RateCurveMsg.displayName = 'proto.qspace.RateCurveMsg';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.qspace.RateCurveMsg.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qspace.RateCurveMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.qspace.RateCurveMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qspace.RateCurveMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.RateCurveMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    pointsList: jspb.Message.toObjectList(msg.getPointsList(),
    proto.qspace.RateCurvePoint.toObject, includeInstance),
    base: (f = msg.getBase()) && DateTimeMsg_pb.DateTimeMsg.toObject(includeInstance, f),
    interpolation: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qspace.RateCurveMsg}
 */
proto.qspace.RateCurveMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qspace.RateCurveMsg;
  return proto.qspace.RateCurveMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qspace.RateCurveMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qspace.RateCurveMsg}
 */
proto.qspace.RateCurveMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.qspace.RateCurvePoint;
      reader.readMessage(value,proto.qspace.RateCurvePoint.deserializeBinaryFromReader);
      msg.addPoints(value);
      break;
    case 2:
      var value = new DateTimeMsg_pb.DateTimeMsg;
      reader.readMessage(value,DateTimeMsg_pb.DateTimeMsg.deserializeBinaryFromReader);
      msg.setBase(value);
      break;
    case 3:
      var value = /** @type {!proto.qspace.RateInterpolation} */ (reader.readEnum());
      msg.setInterpolation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qspace.RateCurveMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qspace.RateCurveMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qspace.RateCurveMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.RateCurveMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.qspace.RateCurvePoint.serializeBinaryToWriter
    );
  }
  f = message.getBase();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      DateTimeMsg_pb.DateTimeMsg.serializeBinaryToWriter
    );
  }
  f = message.getInterpolation();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * repeated RateCurvePoint points = 1;
 * @return {!Array.<!proto.qspace.RateCurvePoint>}
 */
proto.qspace.RateCurveMsg.prototype.getPointsList = function() {
  return /** @type{!Array.<!proto.qspace.RateCurvePoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.qspace.RateCurvePoint, 1));
};


/** @param {!Array.<!proto.qspace.RateCurvePoint>} value */
proto.qspace.RateCurveMsg.prototype.setPointsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.qspace.RateCurvePoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.qspace.RateCurvePoint}
 */
proto.qspace.RateCurveMsg.prototype.addPoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.qspace.RateCurvePoint, opt_index);
};


proto.qspace.RateCurveMsg.prototype.clearPointsList = function() {
  this.setPointsList([]);
};


/**
 * optional DateTimeMsg base = 2;
 * @return {?proto.qspace.DateTimeMsg}
 */
proto.qspace.RateCurveMsg.prototype.getBase = function() {
  return /** @type{?proto.qspace.DateTimeMsg} */ (
    jspb.Message.getWrapperField(this, DateTimeMsg_pb.DateTimeMsg, 2));
};


/** @param {?proto.qspace.DateTimeMsg|undefined} value */
proto.qspace.RateCurveMsg.prototype.setBase = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.qspace.RateCurveMsg.prototype.clearBase = function() {
  this.setBase(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.RateCurveMsg.prototype.hasBase = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional RateInterpolation interpolation = 3;
 * @return {!proto.qspace.RateInterpolation}
 */
proto.qspace.RateCurveMsg.prototype.getInterpolation = function() {
  return /** @type {!proto.qspace.RateInterpolation} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.qspace.RateInterpolation} value */
proto.qspace.RateCurveMsg.prototype.setInterpolation = function(value) {
  jspb.Message.setField(this, 3, value);
};


goog.object.extend(exports, proto.qspace);
