/* eslint-disable */

/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
var ErrorMsg_pb = require('./ErrorMsg_pb.js');
goog.exportSymbol('proto.qspace.ResultMsg', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qspace.ResultMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.qspace.ResultMsg.oneofGroups_);
};
goog.inherits(proto.qspace.ResultMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qspace.ResultMsg.displayName = 'proto.qspace.ResultMsg';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.qspace.ResultMsg.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.qspace.ResultMsg.DataOrErrorCase = {
  DATA_OR_ERROR_NOT_SET: 0,
  DATA: 1,
  ERROR: 2
};

/**
 * @return {proto.qspace.ResultMsg.DataOrErrorCase}
 */
proto.qspace.ResultMsg.prototype.getDataOrErrorCase = function() {
  return /** @type {proto.qspace.ResultMsg.DataOrErrorCase} */(jspb.Message.computeOneofCase(this, proto.qspace.ResultMsg.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.qspace.ResultMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.qspace.ResultMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.qspace.ResultMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.ResultMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    data: (f = msg.getData()) && google_protobuf_any_pb.Any.toObject(includeInstance, f),
    error: (f = msg.getError()) && ErrorMsg_pb.ErrorMsg.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qspace.ResultMsg}
 */
proto.qspace.ResultMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qspace.ResultMsg;
  return proto.qspace.ResultMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qspace.ResultMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qspace.ResultMsg}
 */
proto.qspace.ResultMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    case 2:
      var value = new ErrorMsg_pb.ErrorMsg;
      reader.readMessage(value,ErrorMsg_pb.ErrorMsg.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qspace.ResultMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.qspace.ResultMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qspace.ResultMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.ResultMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      ErrorMsg_pb.ErrorMsg.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Any data = 1;
 * @return {?proto.google.protobuf.Any}
 */
proto.qspace.ResultMsg.prototype.getData = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 1));
};


/** @param {?proto.google.protobuf.Any|undefined} value */
proto.qspace.ResultMsg.prototype.setData = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.qspace.ResultMsg.oneofGroups_[0], value);
};


proto.qspace.ResultMsg.prototype.clearData = function() {
  this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.ResultMsg.prototype.hasData = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ErrorMsg error = 2;
 * @return {?proto.qspace.ErrorMsg}
 */
proto.qspace.ResultMsg.prototype.getError = function() {
  return /** @type{?proto.qspace.ErrorMsg} */ (
    jspb.Message.getWrapperField(this, ErrorMsg_pb.ErrorMsg, 2));
};


/** @param {?proto.qspace.ErrorMsg|undefined} value */
proto.qspace.ResultMsg.prototype.setError = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.qspace.ResultMsg.oneofGroups_[0], value);
};


proto.qspace.ResultMsg.prototype.clearError = function() {
  this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.ResultMsg.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.qspace);
