/* eslint-disable */
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var ProductDetailsMsg_pb = require('./ProductDetailsMsg_pb.js');
var ProductData_pb = require('./ProductData_pb.js');
var DateTimeMsg_pb = require('./DateTimeMsg_pb.js');
var DataKey_pb = require('./DataKey_pb.js');
var RateCurveMsg_pb = require('./RateCurveMsg_pb.js');
var RateMsg_pb = require('./RateMsg_pb.js');
var TimeSeriesMsg_pb = require('./TimeSeriesMsg_pb.js');
var HolidayCalendarMsg_pb = require('./HolidayCalendarMsg_pb.js');
var SwapDefinitionMsg_pb = require('./SwapDefinitionMsg_pb.js');
var Frequency_pb = require('./Frequency_pb.js');
var OptionMsg_pb = require('./OptionMsg_pb.js');
var PriceMsg_pb = require('./PriceMsg_pb.js');
var DoubleMsg_pb = require('./DoubleMsg_pb.js');
var IntMsg_pb = require('./IntMsg_pb.js');
var ExponentMsg_pb = require('./ExponentMsg_pb.js');
var VolSurfaceMsg_pb = require('./VolSurfaceMsg_pb.js');
var ContextMsg_pb = require('./ContextMsg_pb.js');
var LinksMsg_pb = require('./LinksMsg_pb.js');
var PricingResultsMsg_pb = require('./PricingResultsMsg_pb.js');
var PricingOutput_pb = require('./PricingOutput_pb.js');
var GraphMsg_pb = require('./GraphMsg_pb.js');
var StatusMsg_pb = require('./StatusMsg_pb.js');
var ScenarioReportMsg_pb = require('./ScenarioReportMsg_pb.js');
var ScenarioResultsMsg_pb = require('./ScenarioResultsMsg_pb.js');
var ScenarioRequest_pb = require('./ScenarioRequest_pb.js');
var SourcesMsg_pb = require('./SourcesMsg_pb.js');
var DividendStreamMsg_pb = require('./DividendStreamMsg_pb.js');
var SwapMsg_pb = require('./SwapMsg_pb.js');
var IdentityPredicateMsg_pb = require('./IdentityPredicateMsg_pb.js');
var PriceShiftMsg_pb = require('./PriceShiftMsg_pb.js');
var RateCurveShiftMsg_pb = require('./RateCurveShiftMsg_pb.js');
var TimeShiftMsg_pb = require('./TimeShiftMsg_pb.js');
var VolatilityShiftMsg_pb = require('./VolatilityShiftMsg_pb.js');
var VertexMsg_pb = require('./VertexMsg_pb.js');
var VersionMsg_pb = require('./VersionMsg_pb.js');
var UnderlierAtttibutes_pb = require('./UnderlierAtttibutes_pb.js');
var PositionMsg_pb = require('./PositionMsg_pb.js');
goog.exportSymbol('proto.qspace.Wrapper', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.qspace.Wrapper = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.qspace.Wrapper.oneofGroups_);
};
goog.inherits(proto.qspace.Wrapper, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.qspace.Wrapper.displayName = 'proto.qspace.Wrapper';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.qspace.Wrapper.oneofGroups_ = [[2, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41]];

/**
 * @enum {number}
 */
proto.qspace.Wrapper.ContentCase = {
  CONTENT_NOT_SET: 0,
  PRODUCT_DETAILS: 2,
  PRODUCT_DATA: 3,
  DATE_TIME: 4,
  RATE_CURVE: 7,
  TIME_SERIES: 8,
  HOLIDAY_CALENDAR: 9,
  SWAP_DEFINITION: 10,
  FREQUENCY: 11,
  OPTION: 12,
  PRICE: 13,
  VOL_SURFACE: 14,
  CONTEXT: 15,
  LINKS: 16,
  PRICING_RESULTS: 17,
  PRICING_OUTPUT: 18,
  GRAPH: 19,
  STATUS: 20,
  SCENARIO_REPORT: 21,
  SCENARIO_RESULTS: 22,
  SCENARIO_REQUEST: 23,
  SOURCES: 24,
  DOUBLE_MSG: 25,
  INT_MSG: 27,
  EXPONENT: 28,
  RATE: 30,
  DIVIDEND_STREAM: 31,
  SWAP: 32,
  IDENTITY_PREDICATE: 33,
  PRICE_SHIFT: 34,
  RATE_CURVE_SHIFT: 35,
  TIME_SHIFT: 36,
  VOLATILITY_SHIFT: 37,
  VERTEX: 38,
  VERSION: 39,
  UNDERLIER_ATTRIBUTES: 40,
  POSITION: 41
};

/**
 * @return {proto.qspace.Wrapper.ContentCase}
 */
proto.qspace.Wrapper.prototype.getContentCase = function () {
  return /** @type {proto.qspace.Wrapper.ContentCase} */(jspb.Message.computeOneofCase(this, proto.qspace.Wrapper.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto suitable for use in Soy templates.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
   * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
   *     for transitional soy proto support: http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.qspace.Wrapper.prototype.toObject = function (opt_includeInstance) {
    return proto.qspace.Wrapper.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Whether to include the JSPB
   *     instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.qspace.Wrapper} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.qspace.Wrapper.toObject = function (includeInstance, msg) {
    var f, obj = {
      key: (f = msg.getKey()) && DataKey_pb.DataKey.toObject(includeInstance, f),
      productDetails: (f = msg.getProductDetails()) && ProductDetailsMsg_pb.ProductDetailsMsg.toObject(includeInstance, f),
      productData: (f = msg.getProductData()) && ProductData_pb.ProductData.toObject(includeInstance, f),
      dateTime: (f = msg.getDateTime()) && DateTimeMsg_pb.DateTimeMsg.toObject(includeInstance, f),
      rateCurve: (f = msg.getRateCurve()) && RateCurveMsg_pb.RateCurveMsg.toObject(includeInstance, f),
      timeSeries: (f = msg.getTimeSeries()) && TimeSeriesMsg_pb.TimeSeriesMsg.toObject(includeInstance, f),
      holidayCalendar: (f = msg.getHolidayCalendar()) && HolidayCalendarMsg_pb.HolidayCalendarMsg.toObject(includeInstance, f),
      swapDefinition: (f = msg.getSwapDefinition()) && SwapDefinitionMsg_pb.SwapDefinitionMsg.toObject(includeInstance, f),
      frequency: (f = msg.getFrequency()) && Frequency_pb.Frequency.toObject(includeInstance, f),
      option: (f = msg.getOption()) && OptionMsg_pb.OptionMsg.toObject(includeInstance, f),
      price: (f = msg.getPrice()) && PriceMsg_pb.PriceMsg.toObject(includeInstance, f),
      volSurface: (f = msg.getVolSurface()) && VolSurfaceMsg_pb.VolSurfaceMsg.toObject(includeInstance, f),
      context: (f = msg.getContext()) && ContextMsg_pb.ContextMsg.toObject(includeInstance, f),
      links: (f = msg.getLinks()) && LinksMsg_pb.LinksMsg.toObject(includeInstance, f),
      pricingResults: (f = msg.getPricingResults()) && PricingResultsMsg_pb.PricingResultsMsg.toObject(includeInstance, f),
      pricingOutput: (f = msg.getPricingOutput()) && PricingOutput_pb.PricingOutput.toObject(includeInstance, f),
      graph: (f = msg.getGraph()) && GraphMsg_pb.GraphMsg.toObject(includeInstance, f),
      status: (f = msg.getStatus()) && StatusMsg_pb.StatusMsg.toObject(includeInstance, f),
      scenarioReport: (f = msg.getScenarioReport()) && ScenarioReportMsg_pb.ScenarioReportMsg.toObject(includeInstance, f),
      scenarioResults: (f = msg.getScenarioResults()) && ScenarioResultsMsg_pb.ScenarioResultsMsg.toObject(includeInstance, f),
      scenarioRequest: (f = msg.getScenarioRequest()) && ScenarioRequest_pb.ScenarioRequest.toObject(includeInstance, f),
      sources: (f = msg.getSources()) && SourcesMsg_pb.SourcesMsg.toObject(includeInstance, f),
      doubleMsg: (f = msg.getDoubleMsg()) && DoubleMsg_pb.DoubleMsg.toObject(includeInstance, f),
      intMsg: (f = msg.getIntMsg()) && IntMsg_pb.IntMsg.toObject(includeInstance, f),
      exponent: (f = msg.getExponent()) && ExponentMsg_pb.ExponentMsg.toObject(includeInstance, f),
      rate: (f = msg.getRate()) && RateMsg_pb.RateMsg.toObject(includeInstance, f),
      dividendStream: (f = msg.getDividendStream()) && DividendStreamMsg_pb.DividendStreamMsg.toObject(includeInstance, f),
      swap: (f = msg.getSwap()) && SwapMsg_pb.SwapMsg.toObject(includeInstance, f),
      identityPredicate: (f = msg.getIdentityPredicate()) && IdentityPredicateMsg_pb.IdentityPredicateMsg.toObject(includeInstance, f),
      priceShift: (f = msg.getPriceShift()) && PriceShiftMsg_pb.PriceShiftMsg.toObject(includeInstance, f),
      rateCurveShift: (f = msg.getRateCurveShift()) && RateCurveShiftMsg_pb.RateCurveShiftMsg.toObject(includeInstance, f),
      timeShift: (f = msg.getTimeShift()) && TimeShiftMsg_pb.TimeShiftMsg.toObject(includeInstance, f),
      volatilityShift: (f = msg.getVolatilityShift()) && VolatilityShiftMsg_pb.VolatilityShiftMsg.toObject(includeInstance, f),
      vertex: (f = msg.getVertex()) && VertexMsg_pb.VertexMsg.toObject(includeInstance, f),
      version: (f = msg.getVersion()) && VersionMsg_pb.VersionMsg.toObject(includeInstance, f),
      underlierAttributes: (f = msg.getUnderlierAttributes()) && UnderlierAtttibutes_pb.UnderlierAttributesMsg.toObject(includeInstance, f),
      position: (f = msg.getPosition()) && PositionMsg_pb.PositionMsg.toObject(includeInstance, f)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.qspace.Wrapper}
 */
proto.qspace.Wrapper.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.qspace.Wrapper;
  return proto.qspace.Wrapper.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.qspace.Wrapper} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.qspace.Wrapper}
 */
proto.qspace.Wrapper.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new DataKey_pb.DataKey;
        reader.readMessage(value, DataKey_pb.DataKey.deserializeBinaryFromReader);
        msg.setKey(value);
        break;
      case 2:
        var value = new ProductDetailsMsg_pb.ProductDetailsMsg;
        reader.readMessage(value, ProductDetailsMsg_pb.ProductDetailsMsg.deserializeBinaryFromReader);
        msg.setProductDetails(value);
        break;
      case 3:
        var value = new ProductData_pb.ProductData;
        reader.readMessage(value, ProductData_pb.ProductData.deserializeBinaryFromReader);
        msg.setProductData(value);
        break;
      case 4:
        var value = new DateTimeMsg_pb.DateTimeMsg;
        reader.readMessage(value, DateTimeMsg_pb.DateTimeMsg.deserializeBinaryFromReader);
        msg.setDateTime(value);
        break;
      case 7:
        var value = new RateCurveMsg_pb.RateCurveMsg;
        reader.readMessage(value, RateCurveMsg_pb.RateCurveMsg.deserializeBinaryFromReader);
        msg.setRateCurve(value);
        break;
      case 8:
        var value = new TimeSeriesMsg_pb.TimeSeriesMsg;
        reader.readMessage(value, TimeSeriesMsg_pb.TimeSeriesMsg.deserializeBinaryFromReader);
        msg.setTimeSeries(value);
        break;
      case 9:
        var value = new HolidayCalendarMsg_pb.HolidayCalendarMsg;
        reader.readMessage(value, HolidayCalendarMsg_pb.HolidayCalendarMsg.deserializeBinaryFromReader);
        msg.setHolidayCalendar(value);
        break;
      case 10:
        var value = new SwapDefinitionMsg_pb.SwapDefinitionMsg;
        reader.readMessage(value, SwapDefinitionMsg_pb.SwapDefinitionMsg.deserializeBinaryFromReader);
        msg.setSwapDefinition(value);
        break;
      case 11:
        var value = new Frequency_pb.Frequency;
        reader.readMessage(value, Frequency_pb.Frequency.deserializeBinaryFromReader);
        msg.setFrequency(value);
        break;
      case 12:
        var value = new OptionMsg_pb.OptionMsg;
        reader.readMessage(value, OptionMsg_pb.OptionMsg.deserializeBinaryFromReader);
        msg.setOption(value);
        break;
      case 13:
        var value = new PriceMsg_pb.PriceMsg;
        reader.readMessage(value, PriceMsg_pb.PriceMsg.deserializeBinaryFromReader);
        msg.setPrice(value);
        break;
      case 14:
        var value = new VolSurfaceMsg_pb.VolSurfaceMsg;
        reader.readMessage(value, VolSurfaceMsg_pb.VolSurfaceMsg.deserializeBinaryFromReader);
        msg.setVolSurface(value);
        break;
      case 15:
        var value = new ContextMsg_pb.ContextMsg;
        reader.readMessage(value, ContextMsg_pb.ContextMsg.deserializeBinaryFromReader);
        msg.setContext(value);
        break;
      case 16:
        var value = new LinksMsg_pb.LinksMsg;
        reader.readMessage(value, LinksMsg_pb.LinksMsg.deserializeBinaryFromReader);
        msg.setLinks(value);
        break;
      case 17:
        var value = new PricingResultsMsg_pb.PricingResultsMsg;
        reader.readMessage(value, PricingResultsMsg_pb.PricingResultsMsg.deserializeBinaryFromReader);
        msg.setPricingResults(value);
        break;
      case 18:
        var value = new PricingOutput_pb.PricingOutput;
        reader.readMessage(value, PricingOutput_pb.PricingOutput.deserializeBinaryFromReader);
        msg.setPricingOutput(value);
        break;
      case 19:
        var value = new GraphMsg_pb.GraphMsg;
        reader.readMessage(value, GraphMsg_pb.GraphMsg.deserializeBinaryFromReader);
        msg.setGraph(value);
        break;
      case 20:
        var value = new StatusMsg_pb.StatusMsg;
        reader.readMessage(value, StatusMsg_pb.StatusMsg.deserializeBinaryFromReader);
        msg.setStatus(value);
        break;
      case 21:
        var value = new ScenarioReportMsg_pb.ScenarioReportMsg;
        reader.readMessage(value, ScenarioReportMsg_pb.ScenarioReportMsg.deserializeBinaryFromReader);
        msg.setScenarioReport(value);
        break;
      case 22:
        var value = new ScenarioResultsMsg_pb.ScenarioResultsMsg;
        reader.readMessage(value, ScenarioResultsMsg_pb.ScenarioResultsMsg.deserializeBinaryFromReader);
        msg.setScenarioResults(value);
        break;
      case 23:
        var value = new ScenarioRequest_pb.ScenarioRequest;
        reader.readMessage(value, ScenarioRequest_pb.ScenarioRequest.deserializeBinaryFromReader);
        msg.setScenarioRequest(value);
        break;
      case 24:
        var value = new SourcesMsg_pb.SourcesMsg;
        reader.readMessage(value, SourcesMsg_pb.SourcesMsg.deserializeBinaryFromReader);
        msg.setSources(value);
        break;
      case 25:
        var value = new DoubleMsg_pb.DoubleMsg;
        reader.readMessage(value, DoubleMsg_pb.DoubleMsg.deserializeBinaryFromReader);
        msg.setDoubleMsg(value);
        break;
      case 27:
        var value = new IntMsg_pb.IntMsg;
        reader.readMessage(value, IntMsg_pb.IntMsg.deserializeBinaryFromReader);
        msg.setIntMsg(value);
        break;
      case 28:
        var value = new ExponentMsg_pb.ExponentMsg;
        reader.readMessage(value, ExponentMsg_pb.ExponentMsg.deserializeBinaryFromReader);
        msg.setExponent(value);
        break;
      case 30:
        var value = new RateMsg_pb.RateMsg;
        reader.readMessage(value, RateMsg_pb.RateMsg.deserializeBinaryFromReader);
        msg.setRate(value);
        break;
      case 31:
        var value = new DividendStreamMsg_pb.DividendStreamMsg;
        reader.readMessage(value, DividendStreamMsg_pb.DividendStreamMsg.deserializeBinaryFromReader);
        msg.setDividendStream(value);
        break;
      case 32:
        var value = new SwapMsg_pb.SwapMsg;
        reader.readMessage(value, SwapMsg_pb.SwapMsg.deserializeBinaryFromReader);
        msg.setSwap(value);
        break;
      case 33:
        var value = new IdentityPredicateMsg_pb.IdentityPredicateMsg;
        reader.readMessage(value, IdentityPredicateMsg_pb.IdentityPredicateMsg.deserializeBinaryFromReader);
        msg.setIdentityPredicate(value);
        break;
      case 34:
        var value = new PriceShiftMsg_pb.PriceShiftMsg;
        reader.readMessage(value, PriceShiftMsg_pb.PriceShiftMsg.deserializeBinaryFromReader);
        msg.setPriceShift(value);
        break;
      case 35:
        var value = new RateCurveShiftMsg_pb.RateCurveShiftMsg;
        reader.readMessage(value, RateCurveShiftMsg_pb.RateCurveShiftMsg.deserializeBinaryFromReader);
        msg.setRateCurveShift(value);
        break;
      case 36:
        var value = new TimeShiftMsg_pb.TimeShiftMsg;
        reader.readMessage(value, TimeShiftMsg_pb.TimeShiftMsg.deserializeBinaryFromReader);
        msg.setTimeShift(value);
        break;
      case 37:
        var value = new VolatilityShiftMsg_pb.VolatilityShiftMsg;
        reader.readMessage(value, VolatilityShiftMsg_pb.VolatilityShiftMsg.deserializeBinaryFromReader);
        msg.setVolatilityShift(value);
        break;
      case 38:
        var value = new VertexMsg_pb.VertexMsg;
        reader.readMessage(value, VertexMsg_pb.VertexMsg.deserializeBinaryFromReader);
        msg.setVertex(value);
        break;
      case 39:
        var value = new VersionMsg_pb.VersionMsg;
        reader.readMessage(value, VersionMsg_pb.VersionMsg.deserializeBinaryFromReader);
        msg.setVersion(value);
        break;
      case 40:
        var value = new UnderlierAtttibutes_pb.UnderlierAttributesMsg;
        reader.readMessage(value, UnderlierAtttibutes_pb.UnderlierAttributesMsg.deserializeBinaryFromReader);
        msg.setUnderlierAttributes(value);
        break;
      case 41:
        var value = new PositionMsg_pb.PositionMsg;
        reader.readMessage(value, PositionMsg_pb.PositionMsg.deserializeBinaryFromReader);
        msg.setPosition(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.qspace.Wrapper.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.qspace.Wrapper.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.qspace.Wrapper} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.qspace.Wrapper.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      DataKey_pb.DataKey.serializeBinaryToWriter
    );
  }
  f = message.getProductDetails();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      ProductDetailsMsg_pb.ProductDetailsMsg.serializeBinaryToWriter
    );
  }
  f = message.getProductData();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      ProductData_pb.ProductData.serializeBinaryToWriter
    );
  }
  f = message.getDateTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      DateTimeMsg_pb.DateTimeMsg.serializeBinaryToWriter
    );
  }
  f = message.getRateCurve();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      RateCurveMsg_pb.RateCurveMsg.serializeBinaryToWriter
    );
  }
  f = message.getTimeSeries();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      TimeSeriesMsg_pb.TimeSeriesMsg.serializeBinaryToWriter
    );
  }
  f = message.getHolidayCalendar();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      HolidayCalendarMsg_pb.HolidayCalendarMsg.serializeBinaryToWriter
    );
  }
  f = message.getSwapDefinition();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      SwapDefinitionMsg_pb.SwapDefinitionMsg.serializeBinaryToWriter
    );
  }
  f = message.getFrequency();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      Frequency_pb.Frequency.serializeBinaryToWriter
    );
  }
  f = message.getOption();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      OptionMsg_pb.OptionMsg.serializeBinaryToWriter
    );
  }
  f = message.getPrice();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      PriceMsg_pb.PriceMsg.serializeBinaryToWriter
    );
  }
  f = message.getVolSurface();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      VolSurfaceMsg_pb.VolSurfaceMsg.serializeBinaryToWriter
    );
  }
  f = message.getContext();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      ContextMsg_pb.ContextMsg.serializeBinaryToWriter
    );
  }
  f = message.getLinks();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      LinksMsg_pb.LinksMsg.serializeBinaryToWriter
    );
  }
  f = message.getPricingResults();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      PricingResultsMsg_pb.PricingResultsMsg.serializeBinaryToWriter
    );
  }
  f = message.getPricingOutput();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      PricingOutput_pb.PricingOutput.serializeBinaryToWriter
    );
  }
  f = message.getGraph();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      GraphMsg_pb.GraphMsg.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      StatusMsg_pb.StatusMsg.serializeBinaryToWriter
    );
  }
  f = message.getScenarioReport();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      ScenarioReportMsg_pb.ScenarioReportMsg.serializeBinaryToWriter
    );
  }
  f = message.getScenarioResults();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      ScenarioResultsMsg_pb.ScenarioResultsMsg.serializeBinaryToWriter
    );
  }
  f = message.getScenarioRequest();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      ScenarioRequest_pb.ScenarioRequest.serializeBinaryToWriter
    );
  }
  f = message.getSources();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      SourcesMsg_pb.SourcesMsg.serializeBinaryToWriter
    );
  }
  f = message.getDoubleMsg();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      DoubleMsg_pb.DoubleMsg.serializeBinaryToWriter
    );
  }
  f = message.getIntMsg();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      IntMsg_pb.IntMsg.serializeBinaryToWriter
    );
  }
  f = message.getExponent();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      ExponentMsg_pb.ExponentMsg.serializeBinaryToWriter
    );
  }
  f = message.getRate();
  if (f != null) {
    writer.writeMessage(
      30,
      f,
      RateMsg_pb.RateMsg.serializeBinaryToWriter
    );
  }
  f = message.getDividendStream();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      DividendStreamMsg_pb.DividendStreamMsg.serializeBinaryToWriter
    );
  }
  f = message.getSwap();
  if (f != null) {
    writer.writeMessage(
      32,
      f,
      SwapMsg_pb.SwapMsg.serializeBinaryToWriter
    );
  }
  f = message.getIdentityPredicate();
  if (f != null) {
    writer.writeMessage(
      33,
      f,
      IdentityPredicateMsg_pb.IdentityPredicateMsg.serializeBinaryToWriter
    );
  }
  f = message.getPriceShift();
  if (f != null) {
    writer.writeMessage(
      34,
      f,
      PriceShiftMsg_pb.PriceShiftMsg.serializeBinaryToWriter
    );
  }
  f = message.getRateCurveShift();
  if (f != null) {
    writer.writeMessage(
      35,
      f,
      RateCurveShiftMsg_pb.RateCurveShiftMsg.serializeBinaryToWriter
    );
  }
  f = message.getTimeShift();
  if (f != null) {
    writer.writeMessage(
      36,
      f,
      TimeShiftMsg_pb.TimeShiftMsg.serializeBinaryToWriter
    );
  }
  f = message.getVolatilityShift();
  if (f != null) {
    writer.writeMessage(
      37,
      f,
      VolatilityShiftMsg_pb.VolatilityShiftMsg.serializeBinaryToWriter
    );
  }
  f = message.getVertex();
  if (f != null) {
    writer.writeMessage(
      38,
      f,
      VertexMsg_pb.VertexMsg.serializeBinaryToWriter
    );
  }
  f = message.getVersion();
  if (f != null) {
    writer.writeMessage(
      39,
      f,
      VersionMsg_pb.VersionMsg.serializeBinaryToWriter
    );
  }
  f = message.getUnderlierAttributes();
  if (f != null) {
    writer.writeMessage(
      40,
      f,
      UnderlierAtttibutes_pb.UnderlierAttributesMsg.serializeBinaryToWriter
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      41,
      f,
      PositionMsg_pb.PositionMsg.serializeBinaryToWriter
    );
  }
};


/**
 * optional DataKey key = 1;
 * @return {?proto.qspace.DataKey}
 */
proto.qspace.Wrapper.prototype.getKey = function () {
  return /** @type{?proto.qspace.DataKey} */ (
    jspb.Message.getWrapperField(this, DataKey_pb.DataKey, 1));
};


/** @param {?proto.qspace.DataKey|undefined} value */
proto.qspace.Wrapper.prototype.setKey = function (value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.qspace.Wrapper.prototype.clearKey = function () {
  this.setKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasKey = function () {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ProductDetailsMsg product_details = 2;
 * @return {?proto.qspace.ProductDetailsMsg}
 */
proto.qspace.Wrapper.prototype.getProductDetails = function () {
  return /** @type{?proto.qspace.ProductDetailsMsg} */ (
    jspb.Message.getWrapperField(this, ProductDetailsMsg_pb.ProductDetailsMsg, 2));
};


/** @param {?proto.qspace.ProductDetailsMsg|undefined} value */
proto.qspace.Wrapper.prototype.setProductDetails = function (value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearProductDetails = function () {
  this.setProductDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasProductDetails = function () {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ProductData product_data = 3;
 * @return {?proto.qspace.ProductData}
 */
proto.qspace.Wrapper.prototype.getProductData = function () {
  return /** @type{?proto.qspace.ProductData} */ (
    jspb.Message.getWrapperField(this, ProductData_pb.ProductData, 3));
};


/** @param {?proto.qspace.ProductData|undefined} value */
proto.qspace.Wrapper.prototype.setProductData = function (value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearProductData = function () {
  this.setProductData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasProductData = function () {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional DateTimeMsg date_time = 4;
 * @return {?proto.qspace.DateTimeMsg}
 */
proto.qspace.Wrapper.prototype.getDateTime = function () {
  return /** @type{?proto.qspace.DateTimeMsg} */ (
    jspb.Message.getWrapperField(this, DateTimeMsg_pb.DateTimeMsg, 4));
};


/** @param {?proto.qspace.DateTimeMsg|undefined} value */
proto.qspace.Wrapper.prototype.setDateTime = function (value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearDateTime = function () {
  this.setDateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasDateTime = function () {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional RateCurveMsg rate_curve = 7;
 * @return {?proto.qspace.RateCurveMsg}
 */
proto.qspace.Wrapper.prototype.getRateCurve = function () {
  return /** @type{?proto.qspace.RateCurveMsg} */ (
    jspb.Message.getWrapperField(this, RateCurveMsg_pb.RateCurveMsg, 7));
};


/** @param {?proto.qspace.RateCurveMsg|undefined} value */
proto.qspace.Wrapper.prototype.setRateCurve = function (value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearRateCurve = function () {
  this.setRateCurve(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasRateCurve = function () {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional TimeSeriesMsg time_series = 8;
 * @return {?proto.qspace.TimeSeriesMsg}
 */
proto.qspace.Wrapper.prototype.getTimeSeries = function () {
  return /** @type{?proto.qspace.TimeSeriesMsg} */ (
    jspb.Message.getWrapperField(this, TimeSeriesMsg_pb.TimeSeriesMsg, 8));
};


/** @param {?proto.qspace.TimeSeriesMsg|undefined} value */
proto.qspace.Wrapper.prototype.setTimeSeries = function (value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearTimeSeries = function () {
  this.setTimeSeries(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasTimeSeries = function () {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional HolidayCalendarMsg holiday_calendar = 9;
 * @return {?proto.qspace.HolidayCalendarMsg}
 */
proto.qspace.Wrapper.prototype.getHolidayCalendar = function () {
  return /** @type{?proto.qspace.HolidayCalendarMsg} */ (
    jspb.Message.getWrapperField(this, HolidayCalendarMsg_pb.HolidayCalendarMsg, 9));
};


/** @param {?proto.qspace.HolidayCalendarMsg|undefined} value */
proto.qspace.Wrapper.prototype.setHolidayCalendar = function (value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearHolidayCalendar = function () {
  this.setHolidayCalendar(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasHolidayCalendar = function () {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional SwapDefinitionMsg swap_definition = 10;
 * @return {?proto.qspace.SwapDefinitionMsg}
 */
proto.qspace.Wrapper.prototype.getSwapDefinition = function () {
  return /** @type{?proto.qspace.SwapDefinitionMsg} */ (
    jspb.Message.getWrapperField(this, SwapDefinitionMsg_pb.SwapDefinitionMsg, 10));
};


/** @param {?proto.qspace.SwapDefinitionMsg|undefined} value */
proto.qspace.Wrapper.prototype.setSwapDefinition = function (value) {
  jspb.Message.setOneofWrapperField(this, 10, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearSwapDefinition = function () {
  this.setSwapDefinition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasSwapDefinition = function () {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional Frequency frequency = 11;
 * @return {?proto.qspace.Frequency}
 */
proto.qspace.Wrapper.prototype.getFrequency = function () {
  return /** @type{?proto.qspace.Frequency} */ (
    jspb.Message.getWrapperField(this, Frequency_pb.Frequency, 11));
};


/** @param {?proto.qspace.Frequency|undefined} value */
proto.qspace.Wrapper.prototype.setFrequency = function (value) {
  jspb.Message.setOneofWrapperField(this, 11, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearFrequency = function () {
  this.setFrequency(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasFrequency = function () {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional OptionMsg option = 12;
 * @return {?proto.qspace.OptionMsg}
 */
proto.qspace.Wrapper.prototype.getOption = function () {
  return /** @type{?proto.qspace.OptionMsg} */ (
    jspb.Message.getWrapperField(this, OptionMsg_pb.OptionMsg, 12));
};


/** @param {?proto.qspace.OptionMsg|undefined} value */
proto.qspace.Wrapper.prototype.setOption = function (value) {
  jspb.Message.setOneofWrapperField(this, 12, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearOption = function () {
  this.setOption(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasOption = function () {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional PriceMsg price = 13;
 * @return {?proto.qspace.PriceMsg}
 */
proto.qspace.Wrapper.prototype.getPrice = function () {
  return /** @type{?proto.qspace.PriceMsg} */ (
    jspb.Message.getWrapperField(this, PriceMsg_pb.PriceMsg, 13));
};


/** @param {?proto.qspace.PriceMsg|undefined} value */
proto.qspace.Wrapper.prototype.setPrice = function (value) {
  jspb.Message.setOneofWrapperField(this, 13, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearPrice = function () {
  this.setPrice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasPrice = function () {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional VolSurfaceMsg vol_surface = 14;
 * @return {?proto.qspace.VolSurfaceMsg}
 */
proto.qspace.Wrapper.prototype.getVolSurface = function () {
  return /** @type{?proto.qspace.VolSurfaceMsg} */ (
    jspb.Message.getWrapperField(this, VolSurfaceMsg_pb.VolSurfaceMsg, 14));
};


/** @param {?proto.qspace.VolSurfaceMsg|undefined} value */
proto.qspace.Wrapper.prototype.setVolSurface = function (value) {
  jspb.Message.setOneofWrapperField(this, 14, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearVolSurface = function () {
  this.setVolSurface(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasVolSurface = function () {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional ContextMsg context = 15;
 * @return {?proto.qspace.ContextMsg}
 */
proto.qspace.Wrapper.prototype.getContext = function () {
  return /** @type{?proto.qspace.ContextMsg} */ (
    jspb.Message.getWrapperField(this, ContextMsg_pb.ContextMsg, 15));
};


/** @param {?proto.qspace.ContextMsg|undefined} value */
proto.qspace.Wrapper.prototype.setContext = function (value) {
  jspb.Message.setOneofWrapperField(this, 15, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearContext = function () {
  this.setContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasContext = function () {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional LinksMsg links = 16;
 * @return {?proto.qspace.LinksMsg}
 */
proto.qspace.Wrapper.prototype.getLinks = function () {
  return /** @type{?proto.qspace.LinksMsg} */ (
    jspb.Message.getWrapperField(this, LinksMsg_pb.LinksMsg, 16));
};


/** @param {?proto.qspace.LinksMsg|undefined} value */
proto.qspace.Wrapper.prototype.setLinks = function (value) {
  jspb.Message.setOneofWrapperField(this, 16, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearLinks = function () {
  this.setLinks(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasLinks = function () {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional PricingResultsMsg pricing_results = 17;
 * @return {?proto.qspace.PricingResultsMsg}
 */
proto.qspace.Wrapper.prototype.getPricingResults = function () {
  return /** @type{?proto.qspace.PricingResultsMsg} */ (
    jspb.Message.getWrapperField(this, PricingResultsMsg_pb.PricingResultsMsg, 17));
};


/** @param {?proto.qspace.PricingResultsMsg|undefined} value */
proto.qspace.Wrapper.prototype.setPricingResults = function (value) {
  jspb.Message.setOneofWrapperField(this, 17, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearPricingResults = function () {
  this.setPricingResults(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasPricingResults = function () {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional PricingOutput pricing_output = 18;
 * @return {?proto.qspace.PricingOutput}
 */
proto.qspace.Wrapper.prototype.getPricingOutput = function () {
  return /** @type{?proto.qspace.PricingOutput} */ (
    jspb.Message.getWrapperField(this, PricingOutput_pb.PricingOutput, 18));
};


/** @param {?proto.qspace.PricingOutput|undefined} value */
proto.qspace.Wrapper.prototype.setPricingOutput = function (value) {
  jspb.Message.setOneofWrapperField(this, 18, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearPricingOutput = function () {
  this.setPricingOutput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasPricingOutput = function () {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional GraphMsg graph = 19;
 * @return {?proto.qspace.GraphMsg}
 */
proto.qspace.Wrapper.prototype.getGraph = function () {
  return /** @type{?proto.qspace.GraphMsg} */ (
    jspb.Message.getWrapperField(this, GraphMsg_pb.GraphMsg, 19));
};


/** @param {?proto.qspace.GraphMsg|undefined} value */
proto.qspace.Wrapper.prototype.setGraph = function (value) {
  jspb.Message.setOneofWrapperField(this, 19, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearGraph = function () {
  this.setGraph(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasGraph = function () {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional StatusMsg status = 20;
 * @return {?proto.qspace.StatusMsg}
 */
proto.qspace.Wrapper.prototype.getStatus = function () {
  return /** @type{?proto.qspace.StatusMsg} */ (
    jspb.Message.getWrapperField(this, StatusMsg_pb.StatusMsg, 20));
};


/** @param {?proto.qspace.StatusMsg|undefined} value */
proto.qspace.Wrapper.prototype.setStatus = function (value) {
  jspb.Message.setOneofWrapperField(this, 20, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearStatus = function () {
  this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasStatus = function () {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional ScenarioReportMsg scenario_report = 21;
 * @return {?proto.qspace.ScenarioReportMsg}
 */
proto.qspace.Wrapper.prototype.getScenarioReport = function () {
  return /** @type{?proto.qspace.ScenarioReportMsg} */ (
    jspb.Message.getWrapperField(this, ScenarioReportMsg_pb.ScenarioReportMsg, 21));
};


/** @param {?proto.qspace.ScenarioReportMsg|undefined} value */
proto.qspace.Wrapper.prototype.setScenarioReport = function (value) {
  jspb.Message.setOneofWrapperField(this, 21, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearScenarioReport = function () {
  this.setScenarioReport(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasScenarioReport = function () {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional ScenarioResultsMsg scenario_results = 22;
 * @return {?proto.qspace.ScenarioResultsMsg}
 */
proto.qspace.Wrapper.prototype.getScenarioResults = function () {
  return /** @type{?proto.qspace.ScenarioResultsMsg} */ (
    jspb.Message.getWrapperField(this, ScenarioResultsMsg_pb.ScenarioResultsMsg, 22));
};


/** @param {?proto.qspace.ScenarioResultsMsg|undefined} value */
proto.qspace.Wrapper.prototype.setScenarioResults = function (value) {
  jspb.Message.setOneofWrapperField(this, 22, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearScenarioResults = function () {
  this.setScenarioResults(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasScenarioResults = function () {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional ScenarioRequest scenario_request = 23;
 * @return {?proto.qspace.ScenarioRequest}
 */
proto.qspace.Wrapper.prototype.getScenarioRequest = function () {
  return /** @type{?proto.qspace.ScenarioRequest} */ (
    jspb.Message.getWrapperField(this, ScenarioRequest_pb.ScenarioRequest, 23));
};


/** @param {?proto.qspace.ScenarioRequest|undefined} value */
proto.qspace.Wrapper.prototype.setScenarioRequest = function (value) {
  jspb.Message.setOneofWrapperField(this, 23, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearScenarioRequest = function () {
  this.setScenarioRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasScenarioRequest = function () {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional SourcesMsg sources = 24;
 * @return {?proto.qspace.SourcesMsg}
 */
proto.qspace.Wrapper.prototype.getSources = function () {
  return /** @type{?proto.qspace.SourcesMsg} */ (
    jspb.Message.getWrapperField(this, SourcesMsg_pb.SourcesMsg, 24));
};


/** @param {?proto.qspace.SourcesMsg|undefined} value */
proto.qspace.Wrapper.prototype.setSources = function (value) {
  jspb.Message.setOneofWrapperField(this, 24, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearSources = function () {
  this.setSources(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasSources = function () {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional DoubleMsg double_msg = 25;
 * @return {?proto.qspace.DoubleMsg}
 */
proto.qspace.Wrapper.prototype.getDoubleMsg = function () {
  return /** @type{?proto.qspace.DoubleMsg} */ (
    jspb.Message.getWrapperField(this, DoubleMsg_pb.DoubleMsg, 25));
};


/** @param {?proto.qspace.DoubleMsg|undefined} value */
proto.qspace.Wrapper.prototype.setDoubleMsg = function (value) {
  jspb.Message.setOneofWrapperField(this, 25, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearDoubleMsg = function () {
  this.setDoubleMsg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasDoubleMsg = function () {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional IntMsg int_msg = 27;
 * @return {?proto.qspace.IntMsg}
 */
proto.qspace.Wrapper.prototype.getIntMsg = function () {
  return /** @type{?proto.qspace.IntMsg} */ (
    jspb.Message.getWrapperField(this, IntMsg_pb.IntMsg, 27));
};


/** @param {?proto.qspace.IntMsg|undefined} value */
proto.qspace.Wrapper.prototype.setIntMsg = function (value) {
  jspb.Message.setOneofWrapperField(this, 27, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearIntMsg = function () {
  this.setIntMsg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasIntMsg = function () {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * optional ExponentMsg exponent = 28;
 * @return {?proto.qspace.ExponentMsg}
 */
proto.qspace.Wrapper.prototype.getExponent = function () {
  return /** @type{?proto.qspace.ExponentMsg} */ (
    jspb.Message.getWrapperField(this, ExponentMsg_pb.ExponentMsg, 28));
};


/** @param {?proto.qspace.ExponentMsg|undefined} value */
proto.qspace.Wrapper.prototype.setExponent = function (value) {
  jspb.Message.setOneofWrapperField(this, 28, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearExponent = function () {
  this.setExponent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasExponent = function () {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional RateMsg rate = 30;
 * @return {?proto.qspace.RateMsg}
 */
proto.qspace.Wrapper.prototype.getRate = function () {
  return /** @type{?proto.qspace.RateMsg} */ (
    jspb.Message.getWrapperField(this, RateMsg_pb.RateMsg, 30));
};


/** @param {?proto.qspace.RateMsg|undefined} value */
proto.qspace.Wrapper.prototype.setRate = function (value) {
  jspb.Message.setOneofWrapperField(this, 30, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearRate = function () {
  this.setRate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasRate = function () {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * optional DividendStreamMsg dividend_stream = 31;
 * @return {?proto.qspace.DividendStreamMsg}
 */
proto.qspace.Wrapper.prototype.getDividendStream = function () {
  return /** @type{?proto.qspace.DividendStreamMsg} */ (
    jspb.Message.getWrapperField(this, DividendStreamMsg_pb.DividendStreamMsg, 31));
};


/** @param {?proto.qspace.DividendStreamMsg|undefined} value */
proto.qspace.Wrapper.prototype.setDividendStream = function (value) {
  jspb.Message.setOneofWrapperField(this, 31, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearDividendStream = function () {
  this.setDividendStream(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasDividendStream = function () {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional SwapMsg swap = 32;
 * @return {?proto.qspace.SwapMsg}
 */
proto.qspace.Wrapper.prototype.getSwap = function () {
  return /** @type{?proto.qspace.SwapMsg} */ (
    jspb.Message.getWrapperField(this, SwapMsg_pb.SwapMsg, 32));
};


/** @param {?proto.qspace.SwapMsg|undefined} value */
proto.qspace.Wrapper.prototype.setSwap = function (value) {
  jspb.Message.setOneofWrapperField(this, 32, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearSwap = function () {
  this.setSwap(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasSwap = function () {
  return jspb.Message.getField(this, 32) != null;
};


/**
 * optional IdentityPredicateMsg identity_predicate = 33;
 * @return {?proto.qspace.IdentityPredicateMsg}
 */
proto.qspace.Wrapper.prototype.getIdentityPredicate = function () {
  return /** @type{?proto.qspace.IdentityPredicateMsg} */ (
    jspb.Message.getWrapperField(this, IdentityPredicateMsg_pb.IdentityPredicateMsg, 33));
};


/** @param {?proto.qspace.IdentityPredicateMsg|undefined} value */
proto.qspace.Wrapper.prototype.setIdentityPredicate = function (value) {
  jspb.Message.setOneofWrapperField(this, 33, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearIdentityPredicate = function () {
  this.setIdentityPredicate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasIdentityPredicate = function () {
  return jspb.Message.getField(this, 33) != null;
};


/**
 * optional PriceShiftMsg price_shift = 34;
 * @return {?proto.qspace.PriceShiftMsg}
 */
proto.qspace.Wrapper.prototype.getPriceShift = function () {
  return /** @type{?proto.qspace.PriceShiftMsg} */ (
    jspb.Message.getWrapperField(this, PriceShiftMsg_pb.PriceShiftMsg, 34));
};


/** @param {?proto.qspace.PriceShiftMsg|undefined} value */
proto.qspace.Wrapper.prototype.setPriceShift = function (value) {
  jspb.Message.setOneofWrapperField(this, 34, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearPriceShift = function () {
  this.setPriceShift(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasPriceShift = function () {
  return jspb.Message.getField(this, 34) != null;
};


/**
 * optional RateCurveShiftMsg rate_curve_shift = 35;
 * @return {?proto.qspace.RateCurveShiftMsg}
 */
proto.qspace.Wrapper.prototype.getRateCurveShift = function () {
  return /** @type{?proto.qspace.RateCurveShiftMsg} */ (
    jspb.Message.getWrapperField(this, RateCurveShiftMsg_pb.RateCurveShiftMsg, 35));
};


/** @param {?proto.qspace.RateCurveShiftMsg|undefined} value */
proto.qspace.Wrapper.prototype.setRateCurveShift = function (value) {
  jspb.Message.setOneofWrapperField(this, 35, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearRateCurveShift = function () {
  this.setRateCurveShift(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasRateCurveShift = function () {
  return jspb.Message.getField(this, 35) != null;
};


/**
 * optional TimeShiftMsg time_shift = 36;
 * @return {?proto.qspace.TimeShiftMsg}
 */
proto.qspace.Wrapper.prototype.getTimeShift = function () {
  return /** @type{?proto.qspace.TimeShiftMsg} */ (
    jspb.Message.getWrapperField(this, TimeShiftMsg_pb.TimeShiftMsg, 36));
};


/** @param {?proto.qspace.TimeShiftMsg|undefined} value */
proto.qspace.Wrapper.prototype.setTimeShift = function (value) {
  jspb.Message.setOneofWrapperField(this, 36, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearTimeShift = function () {
  this.setTimeShift(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasTimeShift = function () {
  return jspb.Message.getField(this, 36) != null;
};


/**
 * optional VolatilityShiftMsg volatility_shift = 37;
 * @return {?proto.qspace.VolatilityShiftMsg}
 */
proto.qspace.Wrapper.prototype.getVolatilityShift = function () {
  return /** @type{?proto.qspace.VolatilityShiftMsg} */ (
    jspb.Message.getWrapperField(this, VolatilityShiftMsg_pb.VolatilityShiftMsg, 37));
};


/** @param {?proto.qspace.VolatilityShiftMsg|undefined} value */
proto.qspace.Wrapper.prototype.setVolatilityShift = function (value) {
  jspb.Message.setOneofWrapperField(this, 37, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearVolatilityShift = function () {
  this.setVolatilityShift(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasVolatilityShift = function () {
  return jspb.Message.getField(this, 37) != null;
};


/**
 * optional VertexMsg vertex = 38;
 * @return {?proto.qspace.VertexMsg}
 */
proto.qspace.Wrapper.prototype.getVertex = function () {
  return /** @type{?proto.qspace.VertexMsg} */ (
    jspb.Message.getWrapperField(this, VertexMsg_pb.VertexMsg, 38));
};


/** @param {?proto.qspace.VertexMsg|undefined} value */
proto.qspace.Wrapper.prototype.setVertex = function (value) {
  jspb.Message.setOneofWrapperField(this, 38, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearVertex = function () {
  this.setVertex(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasVertex = function () {
  return jspb.Message.getField(this, 38) != null;
};


/**
 * optional VersionMsg version = 39;
 * @return {?proto.qspace.VersionMsg}
 */
proto.qspace.Wrapper.prototype.getVersion = function () {
  return /** @type{?proto.qspace.VersionMsg} */ (
    jspb.Message.getWrapperField(this, VersionMsg_pb.VersionMsg, 39));
};


/** @param {?proto.qspace.VersionMsg|undefined} value */
proto.qspace.Wrapper.prototype.setVersion = function (value) {
  jspb.Message.setOneofWrapperField(this, 39, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearVersion = function () {
  this.setVersion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasVersion = function () {
  return jspb.Message.getField(this, 39) != null;
};


/**
 * optional UnderlierAttributesMsg underlier_attributes = 40;
 * @return {?proto.qspace.UnderlierAttributesMsg}
 */
proto.qspace.Wrapper.prototype.getUnderlierAttributes = function () {
  return /** @type{?proto.qspace.UnderlierAttributesMsg} */ (
    jspb.Message.getWrapperField(this, UnderlierAtttibutes_pb.UnderlierAttributesMsg, 40));
};


/** @param {?proto.qspace.UnderlierAttributesMsg|undefined} value */
proto.qspace.Wrapper.prototype.setUnderlierAttributes = function (value) {
  jspb.Message.setOneofWrapperField(this, 40, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearUnderlierAttributes = function () {
  this.setUnderlierAttributes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasUnderlierAttributes = function () {
  return jspb.Message.getField(this, 40) != null;
};


/**
 * optional PositionMsg position = 41;
 * @return {?proto.qspace.PositionMsg}
 */
proto.qspace.Wrapper.prototype.getPosition = function () {
  return /** @type{?proto.qspace.PositionMsg} */ (
    jspb.Message.getWrapperField(this, PositionMsg_pb.PositionMsg, 41));
};


/** @param {?proto.qspace.PositionMsg|undefined} value */
proto.qspace.Wrapper.prototype.setPosition = function (value) {
  jspb.Message.setOneofWrapperField(this, 41, proto.qspace.Wrapper.oneofGroups_[0], value);
};


proto.qspace.Wrapper.prototype.clearPosition = function () {
  this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.qspace.Wrapper.prototype.hasPosition = function () {
  return jspb.Message.getField(this, 41) != null;
};


goog.object.extend(exports, proto.qspace);
